# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "康测科技"
email: seqhealth@seqhealth.cn
telephone: 027-65527552
description: > # this means to ignore newlines until "baseurl:"
url: "http://www.seqhealth.cn/" # the base hostname & protocol for your site
SSN: #公安备案号
timezone: Asia/Shanghai

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  enable_coderay: true
